# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  "CXX"
  )
# The set of files for implicit dependencies of each language:
set(CMAKE_DEPENDS_CHECK_CXX
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/ADSR.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/ADSR.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Asymp.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Asymp.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/BandedWG.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/BandedWG.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/BeeThree.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/BeeThree.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/BiQuad.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/BiQuad.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Blit.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Blit.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/BlitSaw.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/BlitSaw.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/BlitSquare.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/BlitSquare.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/BlowBotl.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/BlowBotl.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/BlowHole.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/BlowHole.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Bowed.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Bowed.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Brass.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Brass.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Chorus.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Chorus.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Clarinet.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Clarinet.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Delay.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Delay.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/DelayA.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/DelayA.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/DelayL.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/DelayL.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Drummer.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Drummer.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Echo.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Echo.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Envelope.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Envelope.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FM.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FM.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FMVoices.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FMVoices.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FileLoop.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FileLoop.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FileRead.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FileRead.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FileWrite.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FileWrite.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FileWvIn.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FileWvIn.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FileWvOut.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FileWvOut.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Fir.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Fir.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Flute.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Flute.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FormSwep.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FormSwep.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/FreeVerb.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/FreeVerb.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Granulate.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Granulate.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Guitar.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Guitar.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/HevyMetl.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/HevyMetl.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Iir.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Iir.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/InetWvIn.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/InetWvIn.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/InetWvOut.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/InetWvOut.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/JCRev.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/JCRev.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/LentPitShift.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/LentPitShift.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Mandolin.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Mandolin.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Mesh2D.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Mesh2D.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Messager.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Messager.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/MidiFileIn.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/MidiFileIn.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Modal.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Modal.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/ModalBar.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/ModalBar.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Modulate.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Modulate.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Moog.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Moog.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Mutex.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Mutex.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/NRev.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/NRev.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Noise.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Noise.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/OnePole.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/OnePole.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/OneZero.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/OneZero.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/PRCRev.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/PRCRev.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/PercFlut.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/PercFlut.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Phonemes.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Phonemes.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/PitShift.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/PitShift.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Plucked.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Plucked.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/PoleZero.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/PoleZero.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Recorder.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Recorder.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Resonate.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Resonate.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Rhodey.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Rhodey.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/RtAudio.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/RtAudio.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/RtMidi.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/RtMidi.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/RtWvIn.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/RtWvIn.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/RtWvOut.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/RtWvOut.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Sampler.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Sampler.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Saxofony.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Saxofony.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Shakers.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Shakers.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Simple.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Simple.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/SineWave.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/SineWave.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/SingWave.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/SingWave.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Sitar.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Sitar.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Skini.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Skini.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Socket.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Socket.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Sphere.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Sphere.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/StifKarp.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/StifKarp.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Stk.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Stk.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/TapDelay.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/TapDelay.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/TcpClient.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/TcpClient.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/TcpServer.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/TcpServer.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Thread.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Thread.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/TubeBell.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/TubeBell.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Twang.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Twang.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/TwoPole.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/TwoPole.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/TwoZero.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/TwoZero.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/UdpSocket.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/UdpSocket.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/VoicForm.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/VoicForm.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Voicer.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Voicer.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Whistle.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Whistle.cpp.o"
  "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/src/Wurley.cpp" "/Users/jasons/Desktop/ConsoleApp1/cpp/stk/cmake-build-debug/CMakeFiles/stk.dir/src/Wurley.cpp.o"
  )
set(CMAKE_CXX_COMPILER_ID "AppleClang")

# Preprocessor definitions for this target.
set(CMAKE_TARGET_DEFINITIONS_CXX
  "stk_EXPORTS"
  )

# The include file search paths:
set(CMAKE_CXX_TARGET_INCLUDE_PATH
  "../include"
  "../src/include"
  )

# Targets to which this target links.
set(CMAKE_TARGET_LINKED_INFO_FILES
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
