# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

CMakeFiles/stk.dir/src/ADSR.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/ADSR.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/ADSR.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/ADSR.cpp.o: ../src/ADSR.cpp

CMakeFiles/stk.dir/src/Asymp.cpp.o: ../include/Asymp.h
CMakeFiles/stk.dir/src/Asymp.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Asymp.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Asymp.cpp.o: ../src/Asymp.cpp

CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/BandedWG.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/BowTable.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/Function.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/BandedWG.cpp.o: ../src/BandedWG.cpp

CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/BeeThree.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/BeeThree.cpp.o: ../src/BeeThree.cpp

CMakeFiles/stk.dir/src/BiQuad.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/BiQuad.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/BiQuad.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/BiQuad.cpp.o: ../src/BiQuad.cpp

CMakeFiles/stk.dir/src/Blit.cpp.o: ../include/Blit.h
CMakeFiles/stk.dir/src/Blit.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Blit.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Blit.cpp.o: ../src/Blit.cpp

CMakeFiles/stk.dir/src/BlitSaw.cpp.o: ../include/BlitSaw.h
CMakeFiles/stk.dir/src/BlitSaw.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/BlitSaw.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/BlitSaw.cpp.o: ../src/BlitSaw.cpp

CMakeFiles/stk.dir/src/BlitSquare.cpp.o: ../include/BlitSquare.h
CMakeFiles/stk.dir/src/BlitSquare.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/BlitSquare.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/BlitSquare.cpp.o: ../src/BlitSquare.cpp

CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/BlowBotl.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/Function.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/JetTable.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/PoleZero.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/BlowBotl.cpp.o: ../src/BlowBotl.cpp

CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/BlowHole.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/Function.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/PoleZero.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/ReedTable.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/BlowHole.cpp.o: ../src/BlowHole.cpp

CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/BowTable.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/Bowed.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/Function.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Bowed.cpp.o: ../src/Bowed.cpp

CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/Brass.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/PoleZero.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Brass.cpp.o: ../src/Brass.cpp

CMakeFiles/stk.dir/src/Chorus.cpp.o: ../include/Chorus.h
CMakeFiles/stk.dir/src/Chorus.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Chorus.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/Chorus.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Chorus.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Chorus.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Chorus.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Chorus.cpp.o: ../src/Chorus.cpp

CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Clarinet.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Function.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/ReedTable.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Clarinet.cpp.o: ../src/Clarinet.cpp

CMakeFiles/stk.dir/src/Delay.cpp.o: ../include/Delay.h
CMakeFiles/stk.dir/src/Delay.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Delay.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Delay.cpp.o: ../src/Delay.cpp

CMakeFiles/stk.dir/src/DelayA.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/DelayA.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/DelayA.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/DelayA.cpp.o: ../src/DelayA.cpp

CMakeFiles/stk.dir/src/DelayL.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/DelayL.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/DelayL.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/DelayL.cpp.o: ../src/DelayL.cpp

CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/Drummer.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Drummer.cpp.o: ../src/Drummer.cpp

CMakeFiles/stk.dir/src/Echo.cpp.o: ../include/Delay.h
CMakeFiles/stk.dir/src/Echo.cpp.o: ../include/Echo.h
CMakeFiles/stk.dir/src/Echo.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/Echo.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Echo.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Echo.cpp.o: ../src/Echo.cpp

CMakeFiles/stk.dir/src/Envelope.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/Envelope.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Envelope.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Envelope.cpp.o: ../src/Envelope.cpp

CMakeFiles/stk.dir/src/FM.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/FM.cpp.o: ../src/FM.cpp

CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/FMVoices.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/Phonemes.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/FMVoices.cpp.o: ../src/FMVoices.cpp

CMakeFiles/stk.dir/src/FileLoop.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/FileLoop.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/FileLoop.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/FileLoop.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FileLoop.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/FileLoop.cpp.o: ../src/FileLoop.cpp

CMakeFiles/stk.dir/src/FileRead.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/FileRead.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FileRead.cpp.o: ../src/FileRead.cpp

CMakeFiles/stk.dir/src/FileWrite.cpp.o: ../include/FileWrite.h
CMakeFiles/stk.dir/src/FileWrite.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FileWrite.cpp.o: ../src/FileWrite.cpp

CMakeFiles/stk.dir/src/FileWvIn.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/FileWvIn.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/FileWvIn.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FileWvIn.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/FileWvIn.cpp.o: ../src/FileWvIn.cpp

CMakeFiles/stk.dir/src/FileWvOut.cpp.o: ../include/FileWrite.h
CMakeFiles/stk.dir/src/FileWvOut.cpp.o: ../include/FileWvOut.h
CMakeFiles/stk.dir/src/FileWvOut.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FileWvOut.cpp.o: ../include/WvOut.h
CMakeFiles/stk.dir/src/FileWvOut.cpp.o: ../src/FileWvOut.cpp

CMakeFiles/stk.dir/src/Fir.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Fir.cpp.o: ../include/Fir.h
CMakeFiles/stk.dir/src/Fir.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Fir.cpp.o: ../src/Fir.cpp

CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/Flute.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/Function.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/JetTable.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/PoleZero.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Flute.cpp.o: ../src/Flute.cpp

CMakeFiles/stk.dir/src/FormSwep.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/FormSwep.cpp.o: ../include/FormSwep.h
CMakeFiles/stk.dir/src/FormSwep.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FormSwep.cpp.o: ../src/FormSwep.cpp

CMakeFiles/stk.dir/src/FreeVerb.cpp.o: ../include/Delay.h
CMakeFiles/stk.dir/src/FreeVerb.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/FreeVerb.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/FreeVerb.cpp.o: ../include/FreeVerb.h
CMakeFiles/stk.dir/src/FreeVerb.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/FreeVerb.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/FreeVerb.cpp.o: ../src/FreeVerb.cpp

CMakeFiles/stk.dir/src/Granulate.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/Granulate.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Granulate.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Granulate.cpp.o: ../include/Granulate.h
CMakeFiles/stk.dir/src/Granulate.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Granulate.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Granulate.cpp.o: ../src/Granulate.cpp

CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/Fir.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/Guitar.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/Twang.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Guitar.cpp.o: ../src/Guitar.cpp

CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/HevyMetl.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/HevyMetl.cpp.o: ../src/HevyMetl.cpp

CMakeFiles/stk.dir/src/Iir.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Iir.cpp.o: ../include/Iir.h
CMakeFiles/stk.dir/src/Iir.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Iir.cpp.o: ../src/Iir.cpp

CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/InetWvIn.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/Mutex.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/Socket.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/TcpServer.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/Thread.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/UdpSocket.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/InetWvIn.cpp.o: ../src/InetWvIn.cpp

CMakeFiles/stk.dir/src/InetWvOut.cpp.o: ../include/InetWvOut.h
CMakeFiles/stk.dir/src/InetWvOut.cpp.o: ../include/Socket.h
CMakeFiles/stk.dir/src/InetWvOut.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/InetWvOut.cpp.o: ../include/TcpClient.h
CMakeFiles/stk.dir/src/InetWvOut.cpp.o: ../include/UdpSocket.h
CMakeFiles/stk.dir/src/InetWvOut.cpp.o: ../include/WvOut.h
CMakeFiles/stk.dir/src/InetWvOut.cpp.o: ../src/InetWvOut.cpp

CMakeFiles/stk.dir/src/JCRev.cpp.o: ../include/Delay.h
CMakeFiles/stk.dir/src/JCRev.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/JCRev.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/JCRev.cpp.o: ../include/JCRev.h
CMakeFiles/stk.dir/src/JCRev.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/JCRev.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/JCRev.cpp.o: ../src/JCRev.cpp

CMakeFiles/stk.dir/src/LentPitShift.cpp.o: ../include/Delay.h
CMakeFiles/stk.dir/src/LentPitShift.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/LentPitShift.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/LentPitShift.cpp.o: ../include/LentPitShift.h
CMakeFiles/stk.dir/src/LentPitShift.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/LentPitShift.cpp.o: ../src/LentPitShift.cpp

CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/Fir.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/Mandolin.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/Twang.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Mandolin.cpp.o: ../src/Mandolin.cpp

CMakeFiles/stk.dir/src/Mesh2D.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Mesh2D.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Mesh2D.cpp.o: ../include/Mesh2D.h
CMakeFiles/stk.dir/src/Mesh2D.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Mesh2D.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Mesh2D.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Mesh2D.cpp.o: ../src/Mesh2D.cpp

CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/Messager.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/Mutex.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/RtMidi.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/Skini.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/Socket.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/TcpServer.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../include/Thread.h
CMakeFiles/stk.dir/src/Messager.cpp.o: ../src/Messager.cpp

CMakeFiles/stk.dir/src/MidiFileIn.cpp.o: ../include/MidiFileIn.h
CMakeFiles/stk.dir/src/MidiFileIn.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/MidiFileIn.cpp.o: ../src/MidiFileIn.cpp

CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/Modal.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Modal.cpp.o: ../src/Modal.cpp

CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/Modal.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/ModalBar.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/ModalBar.cpp.o: ../src/ModalBar.cpp

CMakeFiles/stk.dir/src/Modulate.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Modulate.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Modulate.cpp.o: ../include/Modulate.h
CMakeFiles/stk.dir/src/Modulate.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Modulate.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Modulate.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Modulate.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Modulate.cpp.o: ../src/Modulate.cpp

CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/FormSwep.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/Moog.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/Sampler.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Moog.cpp.o: ../src/Moog.cpp

CMakeFiles/stk.dir/src/Mutex.cpp.o: ../include/Mutex.h
CMakeFiles/stk.dir/src/Mutex.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Mutex.cpp.o: ../src/Mutex.cpp

CMakeFiles/stk.dir/src/NRev.cpp.o: ../include/Delay.h
CMakeFiles/stk.dir/src/NRev.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/NRev.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/NRev.cpp.o: ../include/NRev.h
CMakeFiles/stk.dir/src/NRev.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/NRev.cpp.o: ../src/NRev.cpp

CMakeFiles/stk.dir/src/Noise.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Noise.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Noise.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Noise.cpp.o: ../src/Noise.cpp

CMakeFiles/stk.dir/src/OnePole.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/OnePole.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/OnePole.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/OnePole.cpp.o: ../src/OnePole.cpp

CMakeFiles/stk.dir/src/OneZero.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/OneZero.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/OneZero.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/OneZero.cpp.o: ../src/OneZero.cpp

CMakeFiles/stk.dir/src/PRCRev.cpp.o: ../include/Delay.h
CMakeFiles/stk.dir/src/PRCRev.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/PRCRev.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/PRCRev.cpp.o: ../include/PRCRev.h
CMakeFiles/stk.dir/src/PRCRev.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/PRCRev.cpp.o: ../src/PRCRev.cpp

CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/PercFlut.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/PercFlut.cpp.o: ../src/PercFlut.cpp

CMakeFiles/stk.dir/src/Phonemes.cpp.o: ../include/Phonemes.h
CMakeFiles/stk.dir/src/Phonemes.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Phonemes.cpp.o: ../src/Phonemes.cpp

CMakeFiles/stk.dir/src/PitShift.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/PitShift.cpp.o: ../include/Effect.h
CMakeFiles/stk.dir/src/PitShift.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/PitShift.cpp.o: ../include/PitShift.h
CMakeFiles/stk.dir/src/PitShift.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/PitShift.cpp.o: ../src/PitShift.cpp

CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/Plucked.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Plucked.cpp.o: ../src/Plucked.cpp

CMakeFiles/stk.dir/src/PoleZero.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/PoleZero.cpp.o: ../include/PoleZero.h
CMakeFiles/stk.dir/src/PoleZero.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/PoleZero.cpp.o: ../src/PoleZero.cpp

CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/Iir.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/Recorder.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Recorder.cpp.o: ../src/Recorder.cpp

CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/Resonate.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Resonate.cpp.o: ../src/Resonate.cpp

CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/Rhodey.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Rhodey.cpp.o: ../src/Rhodey.cpp

CMakeFiles/stk.dir/src/RtAudio.cpp.o: ../include/RtAudio.h
CMakeFiles/stk.dir/src/RtAudio.cpp.o: ../src/RtAudio.cpp

CMakeFiles/stk.dir/src/RtMidi.cpp.o: ../include/RtMidi.h
CMakeFiles/stk.dir/src/RtMidi.cpp.o: ../src/RtMidi.cpp

CMakeFiles/stk.dir/src/RtWvIn.cpp.o: ../include/Mutex.h
CMakeFiles/stk.dir/src/RtWvIn.cpp.o: ../include/RtAudio.h
CMakeFiles/stk.dir/src/RtWvIn.cpp.o: ../include/RtWvIn.h
CMakeFiles/stk.dir/src/RtWvIn.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/RtWvIn.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/RtWvIn.cpp.o: ../src/RtWvIn.cpp

CMakeFiles/stk.dir/src/RtWvOut.cpp.o: ../include/Mutex.h
CMakeFiles/stk.dir/src/RtWvOut.cpp.o: ../include/RtAudio.h
CMakeFiles/stk.dir/src/RtWvOut.cpp.o: ../include/RtWvOut.h
CMakeFiles/stk.dir/src/RtWvOut.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/RtWvOut.cpp.o: ../include/WvOut.h
CMakeFiles/stk.dir/src/RtWvOut.cpp.o: ../src/RtWvOut.cpp

CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/Sampler.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Sampler.cpp.o: ../src/Sampler.cpp

CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Function.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/ReedTable.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Saxofony.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Saxofony.cpp.o: ../src/Saxofony.cpp

CMakeFiles/stk.dir/src/Shakers.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Shakers.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Shakers.cpp.o: ../include/Shakers.h
CMakeFiles/stk.dir/src/Shakers.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Shakers.cpp.o: ../src/Shakers.cpp

CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/Simple.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Simple.cpp.o: ../src/Simple.cpp

CMakeFiles/stk.dir/src/SineWave.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/SineWave.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/SineWave.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/SineWave.cpp.o: ../src/SineWave.cpp

CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/Modulate.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/SingWave.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/SingWave.cpp.o: ../src/SingWave.cpp

CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/Sitar.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Sitar.cpp.o: ../src/Sitar.cpp

CMakeFiles/stk.dir/src/Skini.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Skini.cpp.o: ../include/SKINItbl.h
CMakeFiles/stk.dir/src/Skini.cpp.o: ../include/Skini.h
CMakeFiles/stk.dir/src/Skini.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Skini.cpp.o: ../src/Skini.cpp

CMakeFiles/stk.dir/src/Socket.cpp.o: ../include/Socket.h
CMakeFiles/stk.dir/src/Socket.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Socket.cpp.o: ../src/Socket.cpp

CMakeFiles/stk.dir/src/Sphere.cpp.o: ../include/Sphere.h
CMakeFiles/stk.dir/src/Sphere.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Sphere.cpp.o: ../include/Vector3D.h
CMakeFiles/stk.dir/src/Sphere.cpp.o: ../src/Sphere.cpp

CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/BiQuad.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/StifKarp.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/StifKarp.cpp.o: ../src/StifKarp.cpp

CMakeFiles/stk.dir/src/Stk.cpp.o: ../src/Stk.cpp

CMakeFiles/stk.dir/src/TapDelay.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/TapDelay.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/TapDelay.cpp.o: ../include/TapDelay.h
CMakeFiles/stk.dir/src/TapDelay.cpp.o: ../src/TapDelay.cpp

CMakeFiles/stk.dir/src/TcpClient.cpp.o: ../include/Socket.h
CMakeFiles/stk.dir/src/TcpClient.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/TcpClient.cpp.o: ../include/TcpClient.h
CMakeFiles/stk.dir/src/TcpClient.cpp.o: ../src/TcpClient.cpp

CMakeFiles/stk.dir/src/TcpServer.cpp.o: ../include/Socket.h
CMakeFiles/stk.dir/src/TcpServer.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/TcpServer.cpp.o: ../include/TcpServer.h
CMakeFiles/stk.dir/src/TcpServer.cpp.o: ../src/TcpServer.cpp

CMakeFiles/stk.dir/src/Thread.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Thread.cpp.o: ../include/Thread.h
CMakeFiles/stk.dir/src/Thread.cpp.o: ../src/Thread.cpp

CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/TubeBell.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/TubeBell.cpp.o: ../src/TubeBell.cpp

CMakeFiles/stk.dir/src/Twang.cpp.o: ../include/DelayA.h
CMakeFiles/stk.dir/src/Twang.cpp.o: ../include/DelayL.h
CMakeFiles/stk.dir/src/Twang.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Twang.cpp.o: ../include/Fir.h
CMakeFiles/stk.dir/src/Twang.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Twang.cpp.o: ../include/Twang.h
CMakeFiles/stk.dir/src/Twang.cpp.o: ../src/Twang.cpp

CMakeFiles/stk.dir/src/TwoPole.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/TwoPole.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/TwoPole.cpp.o: ../include/TwoPole.h
CMakeFiles/stk.dir/src/TwoPole.cpp.o: ../src/TwoPole.cpp

CMakeFiles/stk.dir/src/TwoZero.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/TwoZero.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/TwoZero.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/TwoZero.cpp.o: ../src/TwoZero.cpp

CMakeFiles/stk.dir/src/UdpSocket.cpp.o: ../include/Socket.h
CMakeFiles/stk.dir/src/UdpSocket.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/UdpSocket.cpp.o: ../include/UdpSocket.h
CMakeFiles/stk.dir/src/UdpSocket.cpp.o: ../src/UdpSocket.cpp

CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/FormSwep.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Modulate.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/OneZero.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Phonemes.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/SingWave.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/VoicForm.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/VoicForm.cpp.o: ../src/VoicForm.cpp

CMakeFiles/stk.dir/src/Voicer.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Voicer.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Voicer.cpp.o: ../include/Voicer.h
CMakeFiles/stk.dir/src/Voicer.cpp.o: ../src/Voicer.cpp

CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Envelope.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Noise.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/OnePole.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/SKINImsg.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Sphere.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Vector3D.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../include/Whistle.h
CMakeFiles/stk.dir/src/Whistle.cpp.o: ../src/Whistle.cpp

CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/ADSR.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/FM.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/FileLoop.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/FileRead.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/FileWvIn.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/Filter.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/Generator.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/Instrmnt.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/SineWave.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/Stk.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/TwoZero.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/Wurley.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../include/WvIn.h
CMakeFiles/stk.dir/src/Wurley.cpp.o: ../src/Wurley.cpp

